# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages:
  - ggplot2
  - pinp
  - rmarkdown

script:
  - R --vanilla -e "rmarkdown::render('README.Rmd'); rmarkdown::render('IntroductionResearchAssistants.Rmd')" 
  